name: CI

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - "examples/**"
      - "scripts/**"
      - "v2/**"
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - "examples/**"
      - "scripts/**"
      - "v2/**"

concurrency:
  group: readme-sync-${{ github.ref }}
  cancel-in-progress: false

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Test
        run: |
          export TEST_DEBUG=1
          bash ./scripts/run_tests.sh

      - name: Coverage Badge - Generate
        if: github.event_name != 'pull_request'
        uses: tj-actions/coverage-badge-go@v3
        with:
          filename: coverage-percent.out

      - name: Autodocs - Generate
        if: github.event_name != 'pull_request'
        run: |
          npm i -g markdown-autodocs
          markdown-autodocs -c code-block -o ./README.md

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Update README.md"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git pull --rebase origin ${{ github.head_ref || github.ref_name }}
          git push origin HEAD:${{ github.head_ref || github.ref_name }}
