name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run gofmt
      run: |
        OUTPUT=`gofmt -d .`; if [ -n "$OUTPUT" ]; then echo "$OUTPUT"; exit 1; fi

    - name: Build Examples
      run: |
        for i in ./examples/*.go; do go build -v "$i"; done

    - name: Download deltachat-rpc-server and GreenMail
      run: |
        curl -L "https://github.com/deltachat/deltachat-core-rust/releases/download/v1.111.0/deltachat-rpc-server-x86_64" -o deltachat-rpc-server
        curl -L "https://repo1.maven.org/maven2/com/icegreen/greenmail-standalone/2.0.0/greenmail-standalone-2.0.0.jar" -o greenmail-standalone.jar
        chmod +x deltachat-rpc-server

    - name: Test
      run: |
        export PATH="`pwd`:$PATH"
        export GREENMAIL_JAR="`pwd`/greenmail-standalone.jar"
        go test -v ./tests
