name: Sync README

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - "README.md"
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - "README.md"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: cp README.md v2/README.md

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: v2/README.md

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2/README.md
          git commit -m "chore: Update v2/README.md"

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
